# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/ip_single_ram_test.xdc

# IP: ip/ip_single_ram/ip_single_ram.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ip_single_ram || ORIG_REF_NAME==ip_single_ram} -quiet] -quiet
