######################################################################
#
# File name : tb_button_debounce_wave.do
# Created on: Fri Oct 31 11:28:18 +0800 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
