######################################################################
#
# File name : tb_button_debounce_wave.do
# Created on: Wed Aug 13 09:49:04 +0800 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
