######################################################################
#
# File name : tb_button_debounce_compile.do
# Created on: Wed Aug 13 13:40:10 +0800 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
D:\\questasim64_2024.1\\win64\\vlib questa_lib/work
D:\\questasim64_2024.1\\win64\\vlib questa_lib/msim

D:\\questasim64_2024.1\\win64\\vlib questa_lib/msim/xil_defaultlib

D:\\questasim64_2024.1\\win64\\vmap xil_defaultlib questa_lib/msim/xil_defaultlib

D:\\questasim64_2024.1\\win64\\vlog  -incr -mfcu -work xil_defaultlib  \
"../../../../XV_button_debounce.srcs/sources_1/new/button_debounce.v" \
"../../../../XV_button_debounce.srcs/sources_1/new/counter.v" \
"../../../../XV_button_debounce.srcs/sim_1/new/tb_button_debounce.v" \


# compile glbl module
D:\\questasim64_2024.1\\win64\\vlog -work xil_defaultlib "glbl.v"

quit -force

