######################################################################
#
# File name : tb_button_debounce.udo
# Created on: Wed Aug 13 09:49:04 +0800 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
