######################################################################
#
# File name : tb_button_debounce_simulate.do
# Created on: Wed Aug 13 13:40:13 +0800 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -lib xil_defaultlib tb_button_debounce_opt

set NumericStdNoWarnings 1
set StdArithNoWarnings 1

do {tb_button_debounce_wave.do}

view wave
view structure
view signals

do {tb_button_debounce.udo}

run 1000ns
