######################################################################
#
# File name : tb_button_debounce_elaborate.do
# Created on: Wed Aug 13 13:40:11 +0800 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
D:\\questasim64_2024.1\\win64\\vopt +acc=npr -suppress 10016 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip -work xil_defaultlib xil_defaultlib.tb_button_debounce xil_defaultlib.glbl -o tb_button_debounce_opt

quit -force
