# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/tgspock/Github/fpga_learing/xx_fft_lab/xx_fft_lab.srcs/sources_1/ip/dds_ila/dds_ila.xci
# IP: The module: 'dds_ila' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/tgspock/Github/fpga_learing/xx_fft_lab/xx_fft_lab.gen/sources_1/ip/dds_ila/ila_v6_2/constraints/ila_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'dds_ila'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/tgspock/Github/fpga_learing/xx_fft_lab/xx_fft_lab.gen/sources_1/ip/dds_ila/ila_v6_2/constraints/ila.xdc
# XDC: The top module name and the constraint reference have the same name: 'dds_ila'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/tgspock/Github/fpga_learing/xx_fft_lab/xx_fft_lab.gen/sources_1/ip/dds_ila/dds_ila_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dds_ila'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/tgspock/Github/fpga_learing/xx_fft_lab/xx_fft_lab.srcs/sources_1/ip/dds_ila/dds_ila.xci
# IP: The module: 'dds_ila' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/tgspock/Github/fpga_learing/xx_fft_lab/xx_fft_lab.gen/sources_1/ip/dds_ila/ila_v6_2/constraints/ila_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'dds_ila'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/tgspock/Github/fpga_learing/xx_fft_lab/xx_fft_lab.gen/sources_1/ip/dds_ila/ila_v6_2/constraints/ila.xdc
# XDC: The top module name and the constraint reference have the same name: 'dds_ila'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/tgspock/Github/fpga_learing/xx_fft_lab/xx_fft_lab.gen/sources_1/ip/dds_ila/dds_ila_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dds_ila'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
