######################################################################
#
# File name : tb_simple_fsm_wave.do
# Created on: Thu Aug 07 23:31:12 +0800 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
