######################################################################
#
# File name : tb_simple_fsm_elaborate.do
# Created on: Thu Aug 07 23:31:09 +0800 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
D:\\questasim64_2024.1\\win64\\vopt +acc=npr -suppress 10016 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip -work xil_defaultlib xil_defaultlib.tb_simple_fsm xil_defaultlib.glbl -o tb_simple_fsm_opt

quit -force
