######################################################################
#
# File name : tb_simple_fsm_compile.do
# Created on: Thu Aug 07 23:31:07 +0800 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
D:\\questasim64_2024.1\\win64\\vlib questa_lib/work
D:\\questasim64_2024.1\\win64\\vlib questa_lib/msim

D:\\questasim64_2024.1\\win64\\vlib questa_lib/msim/xil_defaultlib

D:\\questasim64_2024.1\\win64\\vmap xil_defaultlib questa_lib/msim/xil_defaultlib

D:\\questasim64_2024.1\\win64\\vlog  -mfcu -work xil_defaultlib  \
"../../../../XIII_simple_fsm.srcs/sources_1/new/simple_fsm.v" \
"../../../../XIII_simple_fsm.srcs/sim_1/new/tb_simple_fsm.v" \


# compile glbl module
D:\\questasim64_2024.1\\win64\\vlog -work xil_defaultlib "glbl.v"

quit -force

