######################################################################
#
# File name : tb_simple_fsm_simulate.do
# Created on: Thu Aug 07 23:31:12 +0800 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -lib xil_defaultlib tb_simple_fsm_opt

set NumericStdNoWarnings 1
set StdArithNoWarnings 1

do {tb_simple_fsm_wave.do}

view wave
view structure
view signals

do {tb_simple_fsm.udo}

run 1000ns
