######################################################################
#
# File name : xvii_top_sim_elaborate.do
# Created on: Thu Oct 30 18:22:53 +0800 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
C:\\questasim64_2020.1\\win64\\vopt +acc=npr -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip -work xil_defaultlib xil_defaultlib.xvii_top_sim xil_defaultlib.glbl -o xvii_top_sim_opt

quit -force
