######################################################################
#
# File name : xvii_top_sim_simulate.do
# Created on: Thu Oct 30 18:22:54 +0800 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -lib xil_defaultlib xvii_top_sim_opt

set NumericStdNoWarnings 1
set StdArithNoWarnings 1

do {xvii_top_sim_wave.do}

view wave
view structure
view signals

do {xvii_top_sim.udo}

run 1000ns
