######################################################################
#
# File name : xvii_top_sim_compile.do
# Created on: Thu Oct 30 18:22:51 +0800 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
C:\\questasim64_2020.1\\win64\\vlib questa_lib/work
C:\\questasim64_2020.1\\win64\\vlib questa_lib/msim

C:\\questasim64_2020.1\\win64\\vlib questa_lib/msim/xil_defaultlib

C:\\questasim64_2020.1\\win64\\vmap xil_defaultlib questa_lib/msim/xil_defaultlib

C:\\questasim64_2020.1\\win64\\vlog  -incr -work xil_defaultlib  \
"../../../../xvii_new_start.srcs/sources_1/new/counter.v" \
"../../../../xvii_new_start.srcs/sources_1/new/xvii_top.v" \
"../../../../xvii_new_start.srcs/sim_1/new/xvii_top_sim.v" \


# compile glbl module
C:\\questasim64_2020.1\\win64\\vlog -work xil_defaultlib "glbl.v"

quit -force

