######################################################################
#
# File name : xvii_top_sim_wave.do
# Created on: Thu Oct 30 18:06:08 +0800 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
