######################################################################
#
# File name : tb_ip_pll_test_wave.do
# Created on: Fri Aug 15 10:45:29 +0800 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
