######################################################################
#
# File name : tb_ip_rom_test_wave.do
# Created on: Fri Aug 15 17:52:17 +0800 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
