######################################################################
#
# File name : tb_ip_pll_test_elaborate.do
# Created on: Fri Aug 15 10:45:26 +0800 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
C:\\questasim64_2020.1\\win64\\vopt +acc=npr -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip -L xpm -work xil_defaultlib xil_defaultlib.tb_ip_pll_test xil_defaultlib.glbl -o tb_ip_pll_test_opt

quit -force
