######################################################################
#
# File name : tb_ip_double_ram_test_wave.do
# Created on: Thu Aug 21 14:42:14 +0800 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
