######################################################################
#
# File name : tb_ip_single_ram_test_compile.do
# Created on: Mon Aug 18 16:08:26 +0800 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
C:\\questasim64_2020.1\\win64\\vlib questa_lib/work
C:\\questasim64_2020.1\\win64\\vlib questa_lib/msim

C:\\questasim64_2020.1\\win64\\vlib questa_lib/msim/xil_defaultlib

C:\\questasim64_2020.1\\win64\\vmap xil_defaultlib questa_lib/msim/xil_defaultlib

C:\\questasim64_2020.1\\win64\\vlog  -incr -work xil_defaultlib  "+incdir+../../../../XVI_ip_test.gen/sources_1/ip/ip_pll_0" \
"../../../../XVI_ip_test.gen/sources_1/ip/ip_single_ram/sim/ip_single_ram.v" \
"../../../../XVI_ip_test.srcs/sources_1/new/ip_single_ram_test.v" \
"../../../../XVI_ip_test.srcs/sources_1/new/ram_write_read.v" \
"../../../../XVI_ip_test.srcs/sim_1/new/tb_ip_single_ram_test.v" \


# compile glbl module
C:\\questasim64_2020.1\\win64\\vlog -work xil_defaultlib "glbl.v"

quit -force

