######################################################################
#
# File name : tb_ip_single_ram_test_elaborate.do
# Created on: Mon Aug 18 16:08:27 +0800 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
C:\\questasim64_2020.1\\win64\\vopt +acc=npr -L xil_defaultlib -L blk_mem_gen_v8_4_4 -L unisims_ver -L unimacro_ver -L secureip -L xpm -work xil_defaultlib xil_defaultlib.tb_ip_single_ram_test xil_defaultlib.glbl -o tb_ip_single_ram_test_opt

quit -force
