######################################################################
#
# File name : tb_ip_single_ram_test_wave.do
# Created on: Mon Aug 18 15:15:23 +0800 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
