######################################################################
#
# File name : tb_ip_single_ram_test_simulate.do
# Created on: Mon Aug 18 16:08:28 +0800 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -lib xil_defaultlib tb_ip_single_ram_test_opt

set NumericStdNoWarnings 1
set StdArithNoWarnings 1

do {tb_ip_single_ram_test_wave.do}

view wave
view structure
view signals

do {tb_ip_single_ram_test.udo}

run 1000ns
