######################################################################
#
# File name : tb_ip_double_ram_test_simulate.do
# Created on: Thu Aug 21 15:33:09 +0800 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -lib xil_defaultlib tb_ip_double_ram_test_opt

set NumericStdNoWarnings 1
set StdArithNoWarnings 1

do {tb_ip_double_ram_test_wave.do}

view wave
view structure
view signals

do {tb_ip_double_ram_test.udo}

run 1000ns
