######################################################################
#
# File name : tb_button_debounce.udo
# Created on: Thu Aug 28 15:51:42 +0800 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
