######################################################################
#
# File name : tb_button_debounce_wave.do
# Created on: Thu Aug 28 15:51:42 +0800 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
