######################################################################
#
# File name : tb_pwm_generate.udo
# Created on: Thu Aug 28 16:59:12 +0800 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
