######################################################################
#
# File name : tb_pwm_generate_elaborate.do
# Created on: Thu Aug 28 17:23:31 +0800 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
C:\\questasim64_2020.1\\win64\\vopt +acc=npr -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip -work xil_defaultlib xil_defaultlib.tb_pwm_generate xil_defaultlib.glbl -o tb_pwm_generate_opt

quit -force
