######################################################################
#
# File name : tb_pwm_generate_compile.do
# Created on: Wed Aug 13 01:06:50 +0800 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
D:\\questasim64_2024.1\\win64\\vlib questa_lib/work
D:\\questasim64_2024.1\\win64\\vlib questa_lib/msim

D:\\questasim64_2024.1\\win64\\vlib questa_lib/msim/xil_defaultlib

D:\\questasim64_2024.1\\win64\\vmap xil_defaultlib questa_lib/msim/xil_defaultlib

D:\\questasim64_2024.1\\win64\\vlog  -incr -mfcu -work xil_defaultlib  \
"../../../../XIV_servo.srcs/sources_1/new/counter.v" \
"../../../../XIV_servo.srcs/sources_1/new/pwm_generate.v" \
"../../../../XIV_servo.srcs/sim_1/new/tb_pwm_generate.v" \


# compile glbl module
D:\\questasim64_2024.1\\win64\\vlog -work xil_defaultlib "glbl.v"

quit -force

