######################################################################
#
# File name : tb_pwm_generate_elaborate.do
# Created on: Wed Aug 13 01:06:52 +0800 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
D:\\questasim64_2024.1\\win64\\vopt +acc=npr -suppress 10016 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip -work xil_defaultlib xil_defaultlib.tb_pwm_generate xil_defaultlib.glbl -o tb_pwm_generate_opt

quit -force
