######################################################################
#
# File name : tb_pwm_generate.udo
# Created on: Tue Aug 12 21:02:44 +0800 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
