######################################################################
#
# File name : tb_pwm_generate_wave.do
# Created on: Tue Aug 12 21:02:44 +0800 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
