######################################################################
#
# File name : tb_pwm_generate_simulate.do
# Created on: Wed Aug 13 01:06:54 +0800 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -lib xil_defaultlib tb_pwm_generate_opt

set NumericStdNoWarnings 1
set StdArithNoWarnings 1

do {tb_pwm_generate_wave.do}

view wave
view structure
view signals

do {tb_pwm_generate.udo}

run 1000ns
