######################################################################
#
# File name : tb_top_compile.do
# Created on: Thu Aug 28 17:28:15 +0800 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
C:\\questasim64_2020.1\\win64\\vlib questa_lib/work
C:\\questasim64_2020.1\\win64\\vlib questa_lib/msim

C:\\questasim64_2020.1\\win64\\vlib questa_lib/msim/xil_defaultlib

C:\\questasim64_2020.1\\win64\\vmap xil_defaultlib questa_lib/msim/xil_defaultlib

C:\\questasim64_2020.1\\win64\\vlog  -incr -work xil_defaultlib  \
"../../../../XIV_servo.srcs/sources_1/imports/new/button_debounce.v" \
"../../../../XIV_servo.srcs/sources_1/imports/new/counter.v" \
"../../../../XIV_servo.srcs/sources_1/imports/new/pwm_generate.v" \
"../../../../XIV_servo.srcs/sources_1/imports/new/servo_level.v" \
"../../../../XIV_servo.srcs/sources_1/imports/new/top.v" \
"../../../../XIV_servo.srcs/sim_1/imports/new/tb_top.v" \


# compile glbl module
C:\\questasim64_2020.1\\win64\\vlog -work xil_defaultlib "glbl.v"

quit -force

