######################################################################
#
# File name : tb_top_elaborate.do
# Created on: Thu Aug 28 17:28:17 +0800 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
C:\\questasim64_2020.1\\win64\\vopt +acc=npr -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip -work xil_defaultlib xil_defaultlib.tb_top xil_defaultlib.glbl -o tb_top_opt

quit -force
