######################################################################
#
# File name : tb_top_wave.do
# Created on: Wed Aug 13 18:31:32 +0800 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
