######################################################################
#
# File name : tb_top_wave.do
# Created on: Thu Aug 28 15:52:44 +0800 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
