######################################################################
#
# File name : tb_top_elaborate.do
# Created on: Wed Aug 13 18:31:31 +0800 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
D:\\questasim64_2024.1\\win64\\vopt +acc=npr -suppress 10016 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip -work xil_defaultlib xil_defaultlib.tb_top xil_defaultlib.glbl -o tb_top_opt

quit -force
