######################################################################
#
# File name : top_wave.do
# Created on: Tue Aug 12 11:10:22 +0800 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
