# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/tgspock/Github/fpga_learing/xx_fft_lab/xx_fft_lab.runs/impl_1/.Xil/Vivado-6150-tgspock-BOHK-WAX9X/dc_drv.0/dc/prj_ip.srcs/sources_1/ip/dbg_hub/dbg_hub.xci
# IP: The module: 'dbg_hub' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/tgspock/Github/fpga_learing/xx_fft_lab/xx_fft_lab.runs/impl_1/.Xil/Vivado-6150-tgspock-BOHK-WAX9X/dc_drv.0/dc/prj_ip.gen/sources_1/ip/dbg_hub/constraints/xsdbm_cc_early.xdc
# XDC: The top module name and the constraint reference have the same name: 'dbg_hub'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/tgspock/Github/fpga_learing/xx_fft_lab/xx_fft_lab.runs/impl_1/.Xil/Vivado-6150-tgspock-BOHK-WAX9X/dc_drv.0/dc/prj_ip.gen/sources_1/ip/dbg_hub/constraints/xsdbm_cc_late.xdc
# XDC: The top module name and the constraint reference have the same name: 'dbg_hub'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/tgspock/Github/fpga_learing/xx_fft_lab/xx_fft_lab.runs/impl_1/.Xil/Vivado-6150-tgspock-BOHK-WAX9X/dc_drv.0/dc/prj_ip.gen/sources_1/ip/dbg_hub/constraints/xsdbm_gc_late.xdc
# XDC: The top module name and the constraint reference have the same name: 'dbg_hub'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/tgspock/Github/fpga_learing/xx_fft_lab/xx_fft_lab.runs/impl_1/.Xil/Vivado-6150-tgspock-BOHK-WAX9X/dc_drv.0/dc/prj_ip.gen/sources_1/ip/dbg_hub/dbg_hub_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dbg_hub'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/tgspock/Github/fpga_learing/xx_fft_lab/xx_fft_lab.runs/impl_1/.Xil/Vivado-6150-tgspock-BOHK-WAX9X/dc_drv.0/dc/prj_ip.srcs/sources_1/ip/dbg_hub/dbg_hub.xci
# IP: The module: 'dbg_hub' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/tgspock/Github/fpga_learing/xx_fft_lab/xx_fft_lab.runs/impl_1/.Xil/Vivado-6150-tgspock-BOHK-WAX9X/dc_drv.0/dc/prj_ip.gen/sources_1/ip/dbg_hub/constraints/xsdbm_cc_early.xdc
# XDC: The top module name and the constraint reference have the same name: 'dbg_hub'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/tgspock/Github/fpga_learing/xx_fft_lab/xx_fft_lab.runs/impl_1/.Xil/Vivado-6150-tgspock-BOHK-WAX9X/dc_drv.0/dc/prj_ip.gen/sources_1/ip/dbg_hub/constraints/xsdbm_cc_late.xdc
# XDC: The top module name and the constraint reference have the same name: 'dbg_hub'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/tgspock/Github/fpga_learing/xx_fft_lab/xx_fft_lab.runs/impl_1/.Xil/Vivado-6150-tgspock-BOHK-WAX9X/dc_drv.0/dc/prj_ip.gen/sources_1/ip/dbg_hub/constraints/xsdbm_gc_late.xdc
# XDC: The top module name and the constraint reference have the same name: 'dbg_hub'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/tgspock/Github/fpga_learing/xx_fft_lab/xx_fft_lab.runs/impl_1/.Xil/Vivado-6150-tgspock-BOHK-WAX9X/dc_drv.0/dc/prj_ip.gen/sources_1/ip/dbg_hub/dbg_hub_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dbg_hub'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
