set_property SRC_FILE_INFO {cfile:D:/GitHub/fpga_learing/XVII_uart/XVII_uart.srcs/constrs_1/new/XVII_uart.xdc rfile:../../../XVII_uart.srcs/constrs_1/new/XVII_uart.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V24 [get_ports sys_clk_p]
set_property src_info {type:XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W19 [get_ports sys_rst_n]
set_property src_info {type:XDC file:1 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E13 [get_ports uart_tx_output]
set_property src_info {type:XDC file:1 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E12 [get_ports uart_rx_input]
