######################################################################
#
# File name : tb_button_debounce.udo
# Created on: Mon Sep 01 10:17:28 +0800 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
