######################################################################
#
# File name : tb_button_debounce_compile.do
# Created on: Thu Oct 09 17:33:15 +0800 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
C:\\questasim64_2020.1\\win64\\vlib questa_lib/work
C:\\questasim64_2020.1\\win64\\vlib questa_lib/msim

C:\\questasim64_2020.1\\win64\\vlib questa_lib/msim/xil_defaultlib

C:\\questasim64_2020.1\\win64\\vmap xil_defaultlib questa_lib/msim/xil_defaultlib

C:\\questasim64_2020.1\\win64\\vlog  -incr -work xil_defaultlib  \
"../../../../XVIII_beep_piano.srcs/sources_1/new/button_debounce.v" \
"../../../../XVIII_beep_piano.srcs/sources_1/new/counter.v" \
"../../../../XVIII_beep_piano.srcs/sim_1/new/tb_button_debounce.v" \


# compile glbl module
C:\\questasim64_2020.1\\win64\\vlog -work xil_defaultlib "glbl.v"

quit -force

