######################################################################
#
# File name : tb_button_debounce_elaborate.do
# Created on: Thu Oct 09 17:33:18 +0800 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
C:\\questasim64_2020.1\\win64\\vopt +acc=npr -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip -work xil_defaultlib xil_defaultlib.tb_button_debounce xil_defaultlib.glbl -o tb_button_debounce_opt

quit -force
