######################################################################
#
# File name : tb_button_debounce_wave.do
# Created on: Mon Sep 01 10:17:28 +0800 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
