######################################################################
#
# File name : tb_breath_led_simulate.do
# Created on: Tue Aug 05 16:59:30 +0800 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -voptargs="+acc" -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip -lib xil_defaultlib xil_defaultlib.tb_breath_led xil_defaultlib.glbl

set NumericStdNoWarnings 1
set StdArithNoWarnings 1

do {tb_breath_led_wave.do}

view wave
view structure
view signals

do {tb_breath_led.udo}

run 1000ns
