######################################################################
#
# File name : tb_breath_led_wave.do
# Created on: Tue Aug 05 16:01:29 +0800 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
