######################################################################
#
# File name : XVII_uart.udo
# Created on: Wed Aug 27 15:10:11 +0800 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
