######################################################################
#
# File name : XVII_uart_compile.do
# Created on: Wed Aug 27 15:10:08 +0800 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
C:\\questasim64_2020.1\\win64\\vlib questa_lib/work
C:\\questasim64_2020.1\\win64\\vlib questa_lib/msim

C:\\questasim64_2020.1\\win64\\vlib questa_lib/msim/xil_defaultlib

C:\\questasim64_2020.1\\win64\\vmap xil_defaultlib questa_lib/msim/xil_defaultlib

C:\\questasim64_2020.1\\win64\\vlog  -incr -work xil_defaultlib  \
"../../../../XVII_uart.srcs/sources_1/new/clock_generator.v" \
"../../../../XVII_uart.srcs/sources_1/new/uart_rx.v" \
"../../../../XVII_uart.srcs/sources_1/new/uart_tx.v" \
"../../../../XVII_uart.srcs/sources_1/new/XVII_uart.v" \


# compile glbl module
C:\\questasim64_2020.1\\win64\\vlog -work xil_defaultlib "glbl.v"

quit -force

