######################################################################
#
# File name : XVII_uart_simulate.do
# Created on: Wed Aug 27 15:10:11 +0800 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -lib xil_defaultlib XVII_uart_opt

set NumericStdNoWarnings 1
set StdArithNoWarnings 1

do {XVII_uart_wave.do}

view wave
view structure
view signals

do {XVII_uart.udo}

run 1000ns
