######################################################################
#
# File name : XVII_uart_elaborate.do
# Created on: Wed Aug 27 15:10:09 +0800 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
C:\\questasim64_2020.1\\win64\\vopt +acc=npr -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip -work xil_defaultlib xil_defaultlib.XVII_uart xil_defaultlib.glbl -o XVII_uart_opt

quit -force
