######################################################################
#
# File name : XVII_uart_wave.do
# Created on: Wed Aug 27 15:10:11 +0800 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
