# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/GitHub/fpga_learing/XVI_ip_test/XVI_ip_test.srcs/sources_1/ip/ip_pll_0/ip_pll_0.xci
# IP: The module: 'ip_pll_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/GitHub/fpga_learing/XVI_ip_test/XVI_ip_test.gen/sources_1/ip/ip_pll_0/ip_pll_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'ip_pll_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/GitHub/fpga_learing/XVI_ip_test/XVI_ip_test.gen/sources_1/ip/ip_pll_0/ip_pll_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'ip_pll_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/GitHub/fpga_learing/XVI_ip_test/XVI_ip_test.gen/sources_1/ip/ip_pll_0/ip_pll_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ip_pll_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: d:/GitHub/fpga_learing/XVI_ip_test/XVI_ip_test.srcs/sources_1/ip/ip_pll_0/ip_pll_0.xci
# IP: The module: 'ip_pll_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/GitHub/fpga_learing/XVI_ip_test/XVI_ip_test.gen/sources_1/ip/ip_pll_0/ip_pll_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'ip_pll_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/GitHub/fpga_learing/XVI_ip_test/XVI_ip_test.gen/sources_1/ip/ip_pll_0/ip_pll_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'ip_pll_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/GitHub/fpga_learing/XVI_ip_test/XVI_ip_test.gen/sources_1/ip/ip_pll_0/ip_pll_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ip_pll_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
