######################################################################
#
# File name : tb_run_led_wave.do
# Created on: Tue Aug 05 13:47:44 +0800 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
