######################################################################
#
# File name : tb_run_led_wave.do
# Created on: Fri Aug 01 18:41:08 +0800 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
