######################################################################
#
# File name : tb_run_led_compile.do
# Created on: Tue Aug 05 13:47:41 +0800 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
D:\\modelsim\\win64\\vlib modelsim_lib/work
D:\\modelsim\\win64\\vlib modelsim_lib/msim

D:\\modelsim\\win64\\vlib modelsim_lib/msim/xil_defaultlib

D:\\modelsim\\win64\\vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib

D:\\modelsim\\win64\\vlog  -incr -work xil_defaultlib  \
"../../../../XI_run_led.srcs/sources_1/new/run_led.v" \
"../../../../XI_run_led.srcs/sim_1/new/tb_run_led.v" \


# compile glbl module
D:\\modelsim\\win64\\vlog -work xil_defaultlib "glbl.v"

quit -force

