######################################################################
#
# File name : tb_run_led_simulate.do
# Created on: Sat Aug 02 23:26:58 +0800 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -voptargs="+acc" -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip -lib xil_defaultlib xil_defaultlib.tb_run_led xil_defaultlib.glbl

set NumericStdNoWarnings 1
set StdArithNoWarnings 1

do {tb_run_led_wave.do}

view wave
view structure
view signals

do {tb_run_led.udo}

run 1000ns
